/*******************************************************************************
 * FILENAME: VarCopies.c
 *
 * PROJECT:
 *    Bitty HTTP
 *
 * FILE DESCRIPTION:
 *    This file has the doc for the WS_GETCopy(), WS_POSTCopy(),
 *    and WS_COOKIECopy().
 *
 * COPYRIGHT:
 *    Copyright (c) 2026 Paul Hutchinson
 *
 *    Permission is hereby granted, free of charge, to any person obtaining a copy
 *    of this software and associated documentation files (the "Software"), to deal
 *    in the Software without restriction, including without limitation the rights
 *    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *    copies of the Software, and to permit persons to whom the Software is
 *    furnished to do so, subject to the following conditions:
 *    
 *    The above copyright notice and this permission notice shall be included in all
 *    copies or substantial portions of the Software.
 *    
 *    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *    SOFTWARE.
 *
 ******************************************************************************/

/*** HEADER FILES TO INCLUDE  ***/
#include "CodeExamples.h"
#include "Pages/Pages.h"
#include "Common/Headers.h"

/*** DEFINES                  ***/

/*** MACROS                   ***/

/*** TYPE DEFINITIONS         ***/

/*** FUNCTION PROTOTYPES      ***/

/*** VARIABLE DEFINITIONS     ***/

const char m_VarCopyHTML[]=
"<h1><span>1</span>Reading GET/POST/COOKIE vars using copies</h1>\n"
"<p>This example will show reading vars using the copy functions (WS_GETCopy()\n"
" / WS_POSTCopy() / WS_COOKIECopy()).</p>\n"
"\n"
"<p>The Copy() versions of the <span class='coderef'>WS_GET()</span> / \n"
"<span class='coderef'>WS_POST()</span> / <span class='coderef'>WS_COOKIE()</span>\n"
"function makes a copy into a buffer instead of just returning a pointer into \n"
"the headers RAM.  You still need to setup the list of expected vars the same \n"
"as the normal versions (these versions call the normal versions internally).\n"
"The Copy() versions are just convenience versions).</p>\n"
"\n"
"<p>\n"
"    This example will only talk about the <span class='coderef'>WS_GETCopy()</span>\n"
"    function but same applies to the <span class='coderef'>WS_POSTCopy()</span>\n"
"    and <span class='coderef'>WS_COOKIECopy()</span> versions.\n"
"</p>\n"
"\n"
"<p>\n"
"    <span class='coderef'>WS_GETCopy()</span> takes 2 extra arguments over\n"
"    <span class='coderef'>WS_GET()</span>.\n"
"    A pointer to a buffer to fill in and the size of the buffer.  You provide\n"
"    the buffer and <span class='coderef'>WS_GETCopy()</span> will copy\n"
"    the value into it.\n"
"</p>\n"
"<p>\n"
"    The return value is set to <span class='coderef'>true</span> when the\n"
"    var is found and fits into the dest buffer.  If it doesn't fit into\n"
"    the dest buffer then the value is still copied but it clipped at the\n"
"    max size.  If the value is not found then the dest buffer is set to\n"
"    blank (\\0).\n"
"</p>\n"
"<p>\n"
"    This allow you to ignore the return value and just use the buffer directly,\n"
"    knowning that it will a have a valid string (but maybe blank or clipped).\n"
"</p>\n"
"<p>\n"
"    So for example you can have code that work like this:\n"
"</p>\n"
"<div class='code'>"
"char Value[10];\n"
"WS_GETCopy(Web,\"FormatDrive\",Value,sizeof(Value));\n"
"if(strcmp(Value,\"yes\")==0)\n"
"{\n"
"    // Do Format...\n"
"}\n"
"else if(strcmp(Value,\"no\")==0)\n"
"{\n"
"    // Do Format anyway...\n"
"}\n"
"</div>\n"
"<p>\n"
"    In this case if the user was to send in \"no please don't\" Value will be\n"
"    set to \"no please\\0\" so no match will be made.  If they don't provide\n"
"    the var then Value will be set to \"\\0\" and will not match.\n"
"</p>\n"
"\n"
"<h2>Files</h2>\n"
;

const char m_VarCopyHTML2[]=
"<h2>FileServer.c</h2>\n"
"<p>The file server is changed to provide a form on the root page and a \n"
"new page to display the values from the form.</p>\n"
"\n"
"<div class='code'>"
"const char *GetArgs[]=\n"
"{\n"
"    \"Name\",\n"
"    \"DoCookie\",\n"
"    \"SetCookieValue\",\n"
"    NULL\n"
"};\n"
"\n"
"const char *PostArgs[]=\n"
"{\n"
"    \"Name\",\n"
"    NULL\n"
"};\n"
"\n"
"const char *CookieArgs[]=\n"
"{\n"
"    \"Name\",\n"
"    NULL\n"
"};\n"
"</div>\n"
"\n"
"<p>We add a list of GET/POST/COOKIE vars that we may want to read when processing a \n"
"page later.  We end the list with NULL to mark the end of the list.  The \n"
"code will loop though this list looking for a NULL entry to stop at.</p>\n"
"\n"
"<p>When a match is made the value of the var will be copied to an \n"
"internal RAM buffer.</p>\n"
"\n"
"<div class='code'>"
"struct FileInfo m_Files[]=\n"
"{\n"
"    /* Filename, Dynamic, Cookies, Gets, Posts, Callback */\n"
"    {\"/\",false,NULL,NULL,NULL,File_Root},\n"
"    {\"/Display.html\",true,CookieArgs,GetArgs,PostArgs,File_Display},\n"
"    {\"/SomeStyle.css\",false,NULL,NULL,NULL,File_SomeStyle},\n"
"    {\"/quit.html\",true,NULL,NULL,NULL,File_Quit},\n"
"};\n"
"</div>\n"
"\n"
"<p>A new page has been added called <span class='coderef'>/Display.html</span>\n"
"that will display what the user has typed into the form from the root \n"
"page.</p>\n"
"\n"
"<div class='code'>"
"const char RootHTML[]=\n"
"\"&lt;!DOCTYPE html&gt;\"\n"
"\"&lt;html&gt;\"\n"
"\"&lt;head&gt;\"\n"
"    \"&lt;title&gt;Bitty HTTP - VarCopy example&lt;/title&gt;\"\n"
"    \"&lt;link rel='stylesheet' href='/SomeStyle.css'&gt;\"\n"
"\"&lt;/head&gt;\"\n"
"\"&lt;body&gt;\"\n"
"    \"&lt;div id='top'&gt;Bitty HTTP Example - VarCopy&lt;/div&gt;\"\n"
"    \"&lt;div id='quitbttn'&gt;&lt;a href='/quit.html'&gt;QUIT&lt;/a&gt;&lt;/div&gt;\"\n"
"    \"&lt;div id='content'&gt;\"\n"
"        \"&lt;div style='border:1px solid black;padding:3px;margin-top:5px;'&gt;\"\n"
"        \"GET example&lt;br/&gt;\"\n"
"        \"&lt;form action='/Display.html' method='GET'&gt;\"\n"
"        \"Input your name:&lt;input name='Name'&gt;&lt;/input&gt; \"\n"
"        \"&lt;input type='submit'&gt;&lt;/input&gt;\"\n"
"        \"&lt;/form&gt;\"\n"
"        \"&lt;/div&gt;\"\n"
"        \"&lt;br/&gt;\"\n"
"        \"&lt;div style='border:1px solid black'&gt;\"\n"
"        \"POST example&lt;br/&gt;\"\n"
"        \"&lt;form action='/Display.html' method='POST'&gt;\"\n"
"        \"Input your name:&lt;input name='Name'&gt;&lt;/input&gt; \"\n"
"        \"&lt;input type='submit'&gt;&lt;/input&gt;\"\n"
"        \"&lt;/form&gt;\"\n"
"        \"&lt;/div&gt;\"\n"
"        \"&lt;br/&gt;\"\n"
"        \"&lt;div style='border:1px solid black'&gt;\"\n"
"        \"COOKIE example&lt;br/&gt;\"\n"
"        \"&lt;form action='/Display.html' method='GET'&gt;\"\n"
"        \"&lt;input type='hidden' name='DoCookie' value='1' /&gt;\"\n"
"        \"Input your name:&lt;input name='SetCookieValue'&gt;&lt;/input&gt; \"\n"
"        \"&lt;input type='submit'&gt;&lt;/input&gt;\"\n"
"        \"&lt;/form&gt;\"\n"
"        \"&lt;/div&gt;\"\n"
"        \"&lt;br/&gt;\"\n"
"    \"&lt;/div&gt;\"\n"
"\"&lt;div id='bottom'&gt;&lt;/div&gt;\"\n"
"\"&lt;/body&gt;\"\n"
"\"&lt;/html&gt;\";\n"
"\n"
"void File_Root(struct WebServer *Web)\n"
"{\n"
"    WS_WriteWhole(Web,RootHTML,sizeof(RootHTML)-1);\n"
"}\n"
"</div>\n"
"\n"
"<p>This now just outputs a 3 forms.  One for GET, one for POST, and one that\n"
"sets the COOKIE, asking the user for their name and going to /Display.html.</p>\n"
"\n"
"<div class='code'>\n"
"const char DisplayHTML_Start[]=\n"
"\"&lt;!DOCTYPE html&gt;\"\n"
"\"&lt;html&gt;\"\n"
"\"&lt;head&gt;\"\n"
"    \"&lt;title&gt;Bitty HTTP - Root&lt;/title&gt;\"\n"
"    \"&lt;link rel='stylesheet' href='/SomeStyle.css'&gt;\"\n"
"\"&lt;/head&gt;\"\n"
"\"&lt;body&gt;\"\n"
"    \"&lt;div id='top'&gt;Bitty HTTP Example - Root&lt;/div&gt;\"\n"
"    \"&lt;div id='quitbttn'&gt;&lt;a href='/quit.html'&gt;QUIT&lt;/a&gt;&lt;/div&gt;\"\n"
"    \"&lt;div id='content'&gt;\";\n"
"const char DisplayHTML_End[]=\n"
"    \"&lt;/div&gt;\"\n"
"\"&lt;div id='bottom'&gt;&lt;/div&gt;\"\n"
"\"&lt;/body&gt;\"\n"
"\"&lt;/html&gt;\";\n"
"\n"
"void File_Display(struct WebServer *Web)\n"
"{\n"
"    char buff[100];\n"
"    char DoingCookie[2];\n"
"    char GetName[10];\n"
"    char PostName[10];\n"
"    char CookieName[10];\n"
"    char SetCookieValue[10];\n"
"    bool GetFound;\n"
"    bool PostFound;\n"
"    bool CookieFound;\n"
"\n"
"    /* Collect all the vars first */\n"
"    GetFound=WS_GETCopy(Web,\"Name\",GetName,sizeof(GetName));\n"
"    PostFound=WS_POSTCopy(Web,\"Name\",PostName,sizeof(PostName));\n"
"    CookieFound=WS_COOKIECopy(Web,\"Name\",CookieName,sizeof(CookieName));\n"
"\n"
"    /* Handle setting the cookie (if needed) */\n"
"    WS_GETCopy(Web,\"DoCookie\",DoingCookie,sizeof(DoingCookie));\n"
"    if(DoingCookie[0]=='1')\n"
"    {\n"
"        /* We use 'SetCookieValue' without checking if it was found because we\n"
"           know it will be set to '\0' if it was not found */\n"
"        WS_GETCopy(Web,\"SetCookieValue\",SetCookieValue,sizeof(SetCookieValue));\n"
"        WS_SetCookie(Web,\"Name\",SetCookieValue,0,NULL,NULL,false,false);\n"
"    }\n"
"\n"
"    /* Start the page */\n"
"    WS_WriteChunk(Web,DisplayHTML_Start,sizeof(DisplayHTML_Start)-1);\n"
"\n"
"    WS_WriteChunkStr(Web,\"&lt;table&gt;\");\n"
"    /************ GET ************/\n"
"    WS_WriteChunkStr(Web,\"&lt;tr&gt;\");\n"
"    WS_WriteChunkStr(Web,\"&lt;td&gt;GET&lt;/td&gt;\");\n"
"\n"
"    snprintf(buff,sizeof(buff),\"&lt;td&gt;Value:\\\"%s\\\"&lt;/td&gt;\",GetName);\n"
"    WS_WriteChunkStr(Web,buff);\n"
"    if(!GetFound)\n"
"        WS_WriteChunkStr(Web,\"&lt;td&gt;Name was not set or was too long&lt;/td&gt;\");\n"
"    else\n"
"        WS_WriteChunkStr(Web,\"&lt;td&gt;&lt;/td&gt;\");\n"
"    WS_WriteChunkStr(Web,\"&lt;/tr&gt;\");\n"
"\n"
"    /************ POST ************/\n"
"    WS_WriteChunkStr(Web,\"&lt;tr&gt;\");\n"
"    WS_WriteChunkStr(Web,\"&lt;td&gt;POST&lt;/td&gt;\");\n"
"\n"
"    snprintf(buff,sizeof(buff),\"&lt;td&gt;Value:\\\"%s\\\"&lt;/td&gt;\",PostName);\n"
"    WS_WriteChunkStr(Web,buff);\n"
"    if(!PostFound)\n"
"        WS_WriteChunkStr(Web,\"&lt;td&gt;Name was not set or was too long&lt;/td&gt;\");\n"
"    else\n"
"        WS_WriteChunkStr(Web,\"&lt;td&gt;&lt;/td&gt;\");\n"
"    WS_WriteChunkStr(Web,\"&lt;/tr&gt;\");\n"
"\n"
"    /************ COOKIE ************/\n"
"    WS_WriteChunkStr(Web,\"&lt;tr&gt;\");\n"
"    WS_WriteChunkStr(Web,\"&lt;td&gt;COOKIE&lt;/td&gt;\");\n"
"\n"
"    snprintf(buff,sizeof(buff),\"&lt;td&gt;Value:\\\"%s\\\"&lt;/td&gt;\",CookieName);\n"
"    WS_WriteChunkStr(Web,buff);\n"
"    if(!CookieFound)\n"
"        WS_WriteChunkStr(Web,\"&lt;td&gt;Name was not set or was too long\");\n"
"    else\n"
"        WS_WriteChunkStr(Web,\"&lt;td&gt;\");\n"
"    WS_WriteChunkStr(Web,\" (Remember the cookie value will be 1 refresh behind)&lt;/td&gt;\");\n"
"    WS_WriteChunkStr(Web,\"&lt;/tr&gt;\");\n"
"\n"
"    WS_WriteChunkStr(Web,\"&lt;/table&gt;\");\n"
"\n"
"    WS_WriteChunk(Web,\"&lt;br/&gt;&lt;br/&gt;&lt;a href='/'&gt;Try again&lt;/a&gt;\",35);\n"
"    WS_WriteChunk(Web,\"&lt;br/&gt;\",5);\n"
"\n"
"    WS_WriteChunk(Web,DisplayHTML_End,sizeof(DisplayHTML_End)-1);\n"
"}\n"
"</div>\n"
"\n"
"<p><span class='coderef'>File_Display()</span> use\n"
"<span class='coderef'>WS_GETCopy()</span>, <span class='coderef'>WS_POSTCopy()</span>,\n"
"<span class='coderef'>WS_COOKIECopy()</span> to read out the vars into stack\n"
"buffers.  You call it with the name of the GET/POST/COOKIE var to read.  \n"
"This name also has to be in the <span class='coderef'>GetArgs</span> /\n"
"<span class='coderef'>PostArgs</span> / <span class='coderef'>CookieArgs</span>\n"
"arrays as well.</p>\n"
"\n"
"<p>As you can see \"DoCookie\" is just used without checking the return code,\n"
"because we only care if it was '1'</p>\n"
;


void File_Doc_VarCopy(struct WebServer *Web)
{
    WS_WriteChunk(Web,m_VarCopyHTML,sizeof(m_VarCopyHTML)-1);
    OutputListOfExampleFiles(Web,e_ExampleCode_VarCopy);
    WS_WriteChunk(Web,m_VarCopyHTML2,sizeof(m_VarCopyHTML2)-1);
}
